#17494 review slack package
slingr-stack/slack-package pull request #2
Opened 2024-12-13 04:10 UTC by germanm98

Pull-request for issue #17505 created by @germanm98

## What it does?

Review the Slack package, added need listeners

## How to test it?
Create a slack app at https://api.slack.com/apps
Add the package to a existing app and set it up.
In your Slack app, subscribe your bot to some slack **events**,
set and **interactive message** and also a **slash command**.
Check that all the webhooks mentioned above arrives to your app.

## Technical notes

There are no technical notes.

## Deployment notes

There are no deployment notes.

2024-12-13 04:15 UTC, pasaperez-slingr commented on listeners/webhooks.js
> +                sys.logs.info('Valid slack event received. Triggering event.');
```suggestion
                sys.logs.info('[slack] Valid slack event received. Triggering event.');
```

2024-12-13 04:16 UTC, pasaperez-slingr commented on package.json
> +            "value": "config.WEBHOOK_SYNC_URL+'/events'"
```suggestion
            "value": "config.WEBHOOK_SYNC_URL+'/events/'"
```

2024-12-13 14:01 UTC, jsanchez-slingr requested changes
Remove unnused methods from user.js and bot.js
Remove the initial table from README.md.
Keep the same format we have for other packages like "zoho" for the package settings
I think we could add some examples for the bot api, slash commands and interactive messages.
Review titles rules for documentation Check resolved comments on this PR: https://github.com/slingr-stack/google-storage-package/pull/1#discussion_r1790138744
And review the Capital case format for titles.
Remove "(latest version)" for HTTP Service dependency
The slack API link does redirect to a 404 page.
Use chatgpt for improving grammar and spelling

2024-12-18 19:35 UTC, pasaperez-slingr commented
![image](https://github.com/user-attachments/assets/8e03315f-b20d-4829-8669-405cad124330)
Just a small request, could you add the link where each webhook should be configured?
Or a route something like Applications -> webhook-> menu1 -> option 23

2024-12-18 20:03 UTC, pasaperez-slingr approved these changes
Great! Thanks @germanm98

2024-12-18 20:03 UTC, merged